### ISSUE TITLE
Integration with phpunit

### ISSUE THREAD

**Issue by joe-gaudet-hs** [danielstjules/pho#19]
Love the look of this, is it possible to get it to run inside of phpunit?

Would be awesome.

**Comment by zxqfox** [comment]
:+1: agree ;-D

**Comment by danielstjules** [comment]
Welcome a PR! But pho isn't a very active project atm.

**Comment by elliotchance** [comment]
[concise](https://github.com/elliotchance/concise) is drop in replacement for PHPUnit. As of version 2.1.0 [it supports Pho](http://concise.readthedocs.org/en/latest/integrations.html#pho).

**Comment by danielstjules** [comment]
Sweet! :)

Going to close this since it's been a while, and I don't have the time to work on it myself.
