### ISSUE TITLE
cannot use globals when running pho

### ISSUE THREAD

**Issue by MitchProbst** [danielstjules/pho#21]
I have been trying to implement pho as a way to test php code for software that we develop at work.  We have a file that will import all of our base system classes which relies on reading out of a config file.

```
$cfg = parse_ini_file($cfg_path, true);

require_once("using.php");



using.php contains a function:

public static function init() {
        global $cfg;

        self::$package_path = $cfg['APPLICATION']['path_app'] . 'ModulePackages/';

        ....use self::$package_path here to load files
    }


```

Inside of the init function the $cfg is null no matter what.

If I run the files from php command line it will load properly.  Is there anything I am missing from pho that will stop my ability to call global $cfg?

**Comment by danielstjules** [comment]
Are you running that file as part of `--bootstrap`? I'll see if I can make a small reproduce case later.

**Comment by MitchProbst** [comment]
I have tried both as a --bootstrap file and also just by requiring the file from within the spec I am trying to run.  Any help would be greatly appreciated.

**Comment by danielstjules** [comment]
What does `print_r(file_exists($cfg_path))` give you if added before $cfg, when ran using pho?

**Comment by danielstjules** [comment]
Looks like this is a bug with pho!

```php
<?php

$foo = 'bar';

class Baz {
  public $foo;

  function __construct() {
    global $foo;
    $this->foo = $foo;
  }
}

describe('Baz', function() {
  it('reads from the global $foo', function() {
    $baz = new Baz();
    expect($baz->foo)->toBe('bar');
  });
});
```

I can't tackle it now, but might be able to look into it tonight

```
$ pho global.php

F

Failures:

"Baz reads from the global $foo" FAILED
/Users/dstjules/Desktop/global.php:17
Expected null to be "bar"

Finished in 0.00156 seconds

1 spec, 1 failure
```

**Comment by MitchProbst** [comment]
The above post was just a small snippet that I took to try and explain the situation.  my $cfg_path is properly set to the full directory of my .ini file.

I'm glad you were able to identify the problem that I have run into.  So far I have really enjoyed getting into Pho but this hiccup has caused quite a headache.

**Comment by danielstjules** [comment]
Oops, you can tell I don't PHP much anymore. This is a limitation, not a bug. The closures themselves don't have access to the global vars. You would need to pass them with `use`.

**Comment by MitchProbst** [comment]
Right, but I don't need access to the global variables inside of my pho testing, I need access to it during the process of auto-loading other classes that need to be tested.

test.php
```
<?php

$test = 'var';

function loadFunc()
{
    global $test;
    echo("I should know that test is var: " . $test);
}

loadFunc();
```

test.spec.php
```
<?php

describe('Pho Testing', function () {

    it('knows 1 equals 1', function () {
        expect(1)->toBe(1);
    });
});
```
If I run pho -b test.php test.spec.php
I get `I should know that test is var: NULL`

If I run pho test.spec.php after adding require_once to the spec file I get the same result.

If I run php test.php I get `I should know that test is var: string(3) "var"`
If I run php test.spec.php I get the same result (it obviously errors out immediately afterwards since describe() isn't defined in php.

Outside of the idea of using globals inside of Pho, which I understand and can work around, I'm unable to use globals anywhere when calling a php file from pho

**Comment by danielstjules** [comment]
Fixed, sorry for the wait! Will tag a new release

**Comment by MitchProbst** [comment]
No worries at all.  Thanks for your help getting this sorted out.
