### ISSUE TITLE
Pho and Mockery - close() - can cause subsequent test to fail

### ISSUE THREAD

**Issue by kjr** [danielstjules/pho#23]
I found when using Pho and Mockery that test failures could cause the subsequent test to fail as well.

I'm using Pho and Mockery and have found I need to use close() a lot. 

Initially I was just doing Mockery::close() at the end of each test, but I found that when a method is called that does not match an expectation, an exception is thrown which means that the close is not called. This causes the next test to fail because the expectation is not met. e.g.

```
describe('some tests', function () {
    it('Should do stuff', function () {
        $mock = Mockery::mock('alias:Some\Thing');
        $mock->shouldReceive('doSomething')
            ->with('bob')
            ->once();

       // Oops, I'm passing the wrong argument, so this test will fail
       $mock->doSomething('alf');

       Mockery::close();
    });

    it('Should do other stuff', function () {
         expect(1 + 1)->toBe(2);

         Mockery::close();
    });
});
```

In this case, the first test will fail because the `$mock->doSomething('alf')` call will throw an exception due to no expectation being configured for that argument. This will mean that the `Mockery::close()` call in that test will not happen. This is all correct and expected! **BUT** the second test will then fail because when it calls `Mockery::close()`, Mockery will report that the expectation has not been met.

The quick answer is to put an `afterEach` in each top level `describe` block that calls `Mockery::close()` **as well as** the `Mockery::close()` inside the test - the one inside the test makes sure that test failures are reported when expectations are not met, and the one in the `afterEach` cleans up any unmet expectations from failed tests.

This is a bit awkward - it would be nice if I could set up global `afterEach` things in the bootstrap or something, rather than add this extra boilerplate to every spec file, but at least update the documentation about using `Mockery::close()` to mention this?

**Comment by danielstjules** [comment]
@kjr You're right, that is a bug. I'd expect to be able to do the following:

``` php
describe('some tests', function () {
    afterEach(function() {
        Mockery::close();
    });

    it('Should do stuff', function () {
        $mock = Mockery::mock('alias:Some\Thing');
        $mock->shouldReceive('doSomething')
            ->with('bob')
            ->once();

       // Oops, I'm passing the wrong argument, so this test will fail
       $mock->doSomething('alf');
    });

    it('Should do other stuff', function () {
         expect(1 + 1)->toBe(2);
    });
});
```

**Comment by kjr** [comment]
That would be great, but I didn't consider that bit a bug - the note in the [readme section on Mockery](https://github.com/danielstjules/pho#mocking) says that you can't fail a test from within the `afterEach`

I think the options here are 

- Do nothing - treat as a known issue, just update the readme to point out the need to do this. Sure, you need to add an `afterEach` to each file and duplicate the `Mockery::close()`, but thats not a big deal - it just took me a little while to figure out what was going on here and how to fix it.
- Allow a global hooks to be set up in a bootstrap file so we can do this kind of thing there. Might be useful for other things too.
- Allow exceptions from `afterEach` to fail the tests, so we don't need a `Mockery::close()` at the end of each test. This would be nice, but people might be relying on the current behaviour

If you have a preference for one of these (or something else!) I can look at implementing it and submit a pull request

**Comment by danielstjules** [comment]
> * Allow a global hooks to be set up in a bootstrap file so we can do this kind of thing there. Might be useful for other things too.
> * Allow exceptions from afterEach to fail the tests, so we don't need a Mockery::close() at the end of each test. This would be nice, but people might be relying on the current behaviour

Both of these sound pretty good to me!

**Comment by danielstjules** [comment]
Added support for global hooks in https://github.com/danielstjules/pho/commit/840badcb13a3d7d550a7c43052b6349cef498f62

**Comment by danielstjules** [comment]
@kjr Support for failing specs from afterEach was added in 1.2.0. :)
https://github.com/danielstjules/pho#mocking
